export default {
  silverPackageFeature: [
    'Monthly Investment Services',
    'Virtual Wallet Account',
    'Virtual & Physical Debit Card',
    'Hotel & lodging financing matching the percentage amounts for each membership package',
    '30% Annual Home Renter & Mortgage payment fees waiver up to $1,250.00',
    '30% Annual Automotive Note Payment fees waiver',
    '30% Annual Home Financing up to $1,250.00 on apartments and residential homes',
    '30% Annual Home eviction fees waiver coverage',
    '30% Annual Automotive financing up to $1,250.00',
    '30% Annual Water Utility fees waiver',
    '30% Annual Electric Utility fees waiver',
    'Car Rental Financing Services',
  ],
  goldPackageFeature: [
    'Monthly Investment Services',
    'Direct Deposit Account',
    'Virtual Wallet Account',
    '24/7 Bail Bond Service',
    'Virtual & Physical Debit Card',
    'Cash Back Rewards',
    'Hotel & lodging financing matching the percentage amounts for each membership package',
    '40% Annual Home Renter & Mortgage payment fees waiver up to $1,550.00',
    '40% Annual Home Financing up to $1,550.00 on apartments and residential homes',
    '40% Annual Home eviction fees waiver coverage',
    '40% Annual Automotive Parts fees waiver up to $300.00',
    '40% Annual Automotive Note Payment fees waiver',
    '40% Annual Automotive financing up to $1,550.00',
    '30% Annual Late Storage Fees Waiver',
    '40% Lawyer fees waiver up to $1,550.00',
    '40% Annual Water Utility fees waiver',
    '40% Annual Electric Utility fees waiver',
    'Car Rental Financing Services',
  ],
  diamondPackageFeature: [
    'Monthly Investment Services',
    'Direct Deposit Account',
    'Virtual Wallet Account',
    'Virtual & Physical Debit Card',
    'Cash Back Rewards',
    '24/7 Bail Bond Service',
    'Hotel & lodging financing matching the percentage amounts for each membership package',
    '50% Annual Bank Account Overdraft fees waiver up to $350.00',
    '50% Annual Home Renter & Mortgage payment fees waiver',
    '50% Appliances financing over $350.00 minimum Down payment',
    '50% Home Financing up to $1,750.00 on apartments and residential homes.',
    '50% Home eviction fees waiver up to $ 350.00',
    '50% Automotive Parts fees waiver up to $350.00',
    '50% Annual Automotive Note Payment fees waiver',
    '40% Annual Automotive financing up to $1,750.00 minimum down payment',
    '30% Annual Late Storage Fees Waiver',
    '50% Lawyer fees waiver up to $1,750.00',
    '50% Home Furniture Financing fees waiver',
    '50% Annual Water Utility fees waiver',
    '50% Annual Electric Utility fees waiver',
    'Car Rental Financing Services',
  ],
  platinumPackageFeature: [
    'Monthly Investment Services',
    'Direct Deposit Account',
    'Virtual Wallet Account',
    'Virtual & Physical Debit Card',
    'Cash Back Rewards',
    '24/7 Bail Bond Service',
    'Hotel & lodging financing matching the percentage amounts for each membership package',
    '60% Annual Bank Account Overdraft fees waiver up to $450.00',
    '60% Appliances Financing up to $450.00',
    '60% Vehicle Registration & License Plate fees Waiver',
    '60% Home Financing up to $2,000.00 on apartments and residential homes.',
    '60% Home eviction fees waiver up to $ 450.00',
    '60% Automotive Parts fees waiver up to $450.00',
    '50% Annual Automotive Note Payment fees waiver',
    '60% Automotive financing up to $2,000.00',
    '60% Lawyer fees waiver up to $2,000.00',
    '60% Annual Home Furniture Financing fees waiver up to $2,000.00',
    '60% Annual Home Improvement or repair fees waiver up to $2,500.00',
    '60% Annual Internet & Cable Late & Activation fees Waiver',
    '60% Annual Late Storage Fees Waiver',
    '60% Annual Home Renter & Mortgage Payment Fees Waiver up to $2,000.00',
    '60% Annual Credit Card fees waiver up to $450.00',
    '60% Annual Water Utility fees waiver',
    '60% Annual Electric Utility fees waiver',
    'Car Rental Financing Services',
  ],
};
