const tabImagePath = '../assets/Images/tabIcons/';
const profileTabImagePath = '../assets/Images/profilePageIcons/';
export default {
  defaultProfile: require('../assets/Images/default_profile.png'),
  OnBoardingBg: require('../assets/Images/OnBoardingBg.png'),
  logo: require('../assets/Images/logo.png'),
  eyeOpen: require('../assets/Images/eyeOpen.png'),
  eyeClose: require('../assets/Images/eyeClose.png'),
  SignStep1: require('../assets/Images/SignStep1.png'),
  dashBorder: require('../assets/Images/dashBorder.png'),
  dropBottom: require('../assets/Images/dropBottom.png'),
  image: require('../assets/Images/image.png'),
  rightArrow: require('../assets/Images/rightArrow.png'),
  leftArrow: require('../assets/Images/LeftArrow.png'),
  building: require('../assets/Images/building.png'),
  upGraph: require('../assets/Images/upGraph.png'),
  checkRound: require('../assets/Images/checkRound.png'),
  bowArrow: require('../assets/Images/bowArrow.png'),
  bottomArrow: require('../assets/Images/bottomArrow.png'),
  coupon: require('../assets/Images/coupon.png'),
  home: require('../assets/Images/home.png'),
  home3: require('../assets/Images/home3.png'),
  wallet: require('../assets/Images/wallet.png'),

  suitcase: require('../assets/Images/suitcase.png'),
  homeWithMen: require('../assets/Images/homeWithMen.png'),
  paypalLogo: require('../assets/Images/paypalLogo.png'),
  masterCardLogo: require('../assets/Images/masterCardLogo.png'),
  creditCard: require('../assets/Images/creditCard.png'),
  profile: require('../assets/Images/profile.png'),

  // tabs icons
  HomeActive: require(tabImagePath + 'HomeActive.png'),
  HomeInactive: require(tabImagePath + 'HomeInactive.png'),
  CardActive: require(tabImagePath + 'CardActive.png'),
  CardInactive: require(tabImagePath + 'CardInactive.png'),
  LoanActive: require(tabImagePath + 'LoanActive.png'),
  LoanInactive: require(tabImagePath + 'LoanInactive.png'),
  profileActive: require(tabImagePath + 'profileActive.png'),
  profileInactive: require(tabImagePath + 'profileInactive.png'),

  notificationBell: require('../assets/Images/notificationBell.png'),
  plusIcon: require('../assets/Images/plusIcon.png'),
  percentageIcon: require('../assets/Images/percentageIcon.png'),
  nexusPayLogo: require('../assets/Images/nexusPayLogo.png'),
  visalogo: require('../assets/Images/visalogo.png'),
  billPay: require('../assets/Images/billPay.png'),
  dataImg: require('../assets/Images/dataImg.png'),
  goals: require('../assets/Images/goals.png'),
  receive: require('../assets/Images/receive.png'),
  send: require('../assets/Images/send.png'),
  spendImg: require('../assets/Images/spendImg.png'),
  savedImg: require('../assets/Images/savedImg.png'),
  Search: require('../assets/Images/Search.png'),
  Calendar: require('../assets/Images/Calendar.png'),
  Calendar2: require('../assets/Images/calender2.png'),
  Calendar3: require('../assets/Images/calender3.png'),
  NetflixLogo: require('../assets/Images/NetflixLogo.png'),
  rightArrowWithBg: require('../assets/Images/rightArrowWithBg.png'),
  futureImage: require('../assets/Images/futureImage.png'),
  treeIcon: require('../assets/Images/treeIcon.png'),
  cardBack: require('../assets/Images/cardBack.png'),
  moneyBag: require('../assets/Images/moneyBag.png'),
  masterCardLogo1: require('../assets/Images/masterCardLogo1.png'),
  closeSquare: require('../assets/Images/closeSquare.png'),
  usd: require('../assets/Images/usd.png'),
  ngn: require('../assets/Images/ngn.png'),
  myr: require('../assets/Images/myr.png'),
  arrowdownWhite: require('../assets/Images/arrowdownWhite.png'),
  bankImg: require('../assets/Images/bankImg.png'),
  cardWithBorder: require('../assets/Images/cardWithBorder.png'),

  // profile tab icons
  arowRight: require(profileTabImagePath + 'arowRight.png'),
  claim: require(profileTabImagePath + 'claim.png'),
  edit: require(profileTabImagePath + 'edit.png'),
  legalDoc: require(profileTabImagePath + 'legalDoc.png'),
  lock: require(profileTabImagePath + 'lock.png'),
  logout: require(profileTabImagePath + 'logout.png'),
  manageCard: require(profileTabImagePath + 'manageCard.png'),
  payCycle: require(profileTabImagePath + 'payCycle.png'),
  payments: require(profileTabImagePath + 'payments.png'),
  propertyHome: require(profileTabImagePath + 'propertyHome.png'),
  questionMark: require(profileTabImagePath + 'questionMark.png'),
  refferal: require(profileTabImagePath + 'refferal.png'),
  roundUp: require(profileTabImagePath + 'roundUp.png'),
  subscriptionPackage: require(profileTabImagePath + 'subscriptionPackage.png'),
  termsAndCondition: require(profileTabImagePath + 'termsAndCondition.png'),
  transactions: require(profileTabImagePath + 'transactions.png'),

  bgImage: require('../assets/Images/changePasswordBg.png'),
  sendMoneyBg: require('../assets/Images/sendMoneyBg.png'),
  scanner: require('../assets/Images/scanner.png'),
  search2: require('../assets/Images/search2.png'),
  scanQrCode: require('../assets/Images/scanQrCode.png'),
  dollar: require('../assets/Images/dollar.png'),
  dollar2: require('../assets/Images/dollar2.png'),
  backSpace: require('../assets/Images/backSpace.png'),
  successSendBg: require('../assets/Images/SuccessSendBg.png'),
  paymentSuccess: require('../assets/Images/paymentSuccess.gif'),
  lockIcon: require('../assets/Images/lockIcon.png'),
  Lockgreen: require('../assets/Images/Lockgreen.png'),
  toggleDisable: require('../assets/Images/toggleDisable.png'),
  toggleEnable: require('../assets/Images/toggleEnable.png'),
  bill: require('../assets/Images/bill.png'),
  qrcode: require('../assets/Images/qrcode.png'),
  sendBtn: require('../assets/Images/sendBtn.png'),
  myGoalsHeaderBg: require('../assets/Images/myGoalsHeaderBg.png'),
  home2: require('../assets/Images/home2.png'),
  car: require('../assets/Images/car.png'),
  umbrella: require('../assets/Images/umbrella.png'),
  book: require('../assets/Images/book.png'),
  camera: require('../assets/Images/camera.png'),
  doubleRightArrow: require('../assets/Images/doubleRightArrow.png'),
  trolly: require('../assets/Images/trolly.png'),

  basedWeekly: require('../assets/Images/basedWeekly.png'),
  dailyImage: require('../assets/Images/dailyImage.png'),
  sliderImage: require('../assets/Images/sliderImage.png'),
  heart: require('../assets/Images/heart.png'),
  heart2: require('../assets/Images/heart2.png'),
  plot: require('../assets/Images/plot.png'),
  dummyImg: require('../assets/Images/dummyImg.png'),
  star: require('../assets/Images/star.png'),
  starHalf: require('../assets/Images/starHalf.png'),
  upload: require('../assets/Images/upload.png'),
  discountIcon: require('../assets/Images/discountIcon.png'),
  changePasswordLogo: require('../assets/Images/changePasswordLogo.png'),
  floorPlan: require('../assets/Images/floorPlan.png'),
  confirmedTick: require('../assets/Images/confirmedTick.png'),
  Sorting: require('../assets/Images/Sorting.png'),
  editPen: require('../assets/Images/editPen.png'),
  pen: require('../assets/Images/pen.png'),
  flag: require('../assets/Images/flag.png'),
  uploadDoc: require('../assets/Images/uploadDoc.png'),
  referralImage: require('../assets/Images/referralImage.png'),
  logoWithoutBorder: require('../assets/Images/logoWithoutBorder.png'),
  logoWithBorder: require('../assets/Images/logoWithBorder.png'),
  timeIcon: require('../assets/Images/timeIcon.png'),
  phoneIcon: require('../assets/Images/phoneIcon.png'),
  mailIcon: require('../assets/Images/mailIcon.png'),
  faxIcon: require('../assets/Images/faxIcon.png'),
  downArrow: require('../assets/Images/downArrow.png'),
  dataBg1: require('../assets/Images/dataBg1.png'),
  dataBg2: require('../assets/Images/dataBg2.png'),

  graph: require('../assets/Images/graph.png'),
  roundTopArrow: require('../assets/Images/roundTopArrow.png'),
  carbonDocument: require('../assets/Images/carbonDocument.png'),
  videoMessage: require('../assets/Images/videoMessage.png'),
  addCardLogo: require('../assets/Images/AddCardLogo.png'),
  bankLogo: require('../assets/Images/bankLogo.png'),
  medicine: require('../assets/Images/medicine.png'),
  coffee: require('../assets/Images/coffee.png'),
  restaurant: require('../assets/Images/restaurant.png'),
  claimIcon:  require('../assets/Images/claimIcon.png'),
  dukeEnergy: require('../assets/Images/dukeEnergy.png'),
  weEnergy: require('../assets/Images/weEnergy.png'),
  dukelogo: require('../assets/Images/dukelogo.png'),

  receiptIcon: require('../assets/Images/receiptIcon.png'),
  claimIcon1: require('../assets/Images/claimIcon1.png'),
  marketPlaceIcon: require('../assets/Images/marketPlaceIcon.png'),
  investmentIcon: require('../assets/Images/investmentIcon.png'),
  insuranceIcon:  require('../assets/Images/insuranceIcon.png'),
  phoneIcon1: require('../assets/Images/phoneIcon1.png'),
  internetIcon: require('../assets/Images/internetIcon.png'),
  electicityIcon: require('../assets/Images/electicityIcon.png'),

  autoInsurance: require('../assets/Images/autoInsurance.png'),
  insurancePolicy: require('../assets/Images/insurancePolicy.png'),
  healthInsurance: require('../assets/Images/healthInsurance.png'),
  dentalIsurance: require('../assets/Images/dentalIsurance.png'),
  visionInsurance:  require('../assets/Images/visionInsurance.png'),
  homeInsurance: require('../assets/Images/homeInsurance.png'),
  carLogo: require('../assets/Images/carLogo.png'),
  trackClaim: require('../assets/Images/trackClaim.png'),
  motoLogo: require('../assets/Images/motoLogo.png'),

  carlogo1: require('../assets/Images/carlogo1.png'),
  edit1: require('../assets/Images/edit1.png'),
  download1: require('../assets/Images/download1.png'),
  claimIcon3: require('../assets/Images/claimIcon3.png'),

  parents: require('../assets/Images/parents.png'),
  children: require('../assets/Images/children.png'),
  spouse: require('../assets/Images/spouse.png'),
  self: require('../assets/Images/self.png'),
  locationIcon: require('../assets/Images/locationIcon.png'),
  greenDiscount: require('../assets/Images/greenDiscount.png'),
  ticketStar: require('../assets/Images/ticketStar.png'),
  img1: require('../assets/Images/img1.png'),
  img2: require('../assets/Images/img2.png'),
  img3: require('../assets/Images/img3.png'),
  img4: require('../assets/Images/img4.png'),
  filterIcon: require('../assets/Images/filterIcon.png'),
  successTick: require('../assets/Images/successTick.png'),
  successIconReceipt: require('../assets/Images/successIconReceipt.png'),
  closeIconWithBorder: require('../assets/Images/closeIconWithBorder.png'),
  receiptDownload: require('../assets/Images/receiptDownload.png'),
  receiptbg: require('../assets/Images/receiptbg.png'),
  locIcon: require('../assets/Images/locIcon.png'),
  calenderIcon: require('../assets/Images/calenderIcon.png'),
  houses: require('../assets/Images/houses.png'),
  townhome: require('../assets/Images/townhome.png'),
  condos: require('../assets/Images/condos.png'),
  apartment: require('../assets/Images/apartment.png'),
  car2: require('../assets/Images/car2.png'),
  car3: require('../assets/Images/car3.png'),
  marketplaceHeaderBg: require('../assets/Images/marketplaceHeaderBg.png'),
  car5: require('../assets/Images/car5.png'),
  car6: require('../assets/Images/car6.png'),
  car8: require('../assets/Images/car8.png'),
  car9: require('../assets/Images/car9.png'),
  car10: require('../assets/Images/car10.png'),
  car11: require('../assets/Images/car11.png'),
  wheel: require('../assets/Images/wheel.png'),
  seat: require('../assets/Images/seat.png'),
  safety: require('../assets/Images/safety.png'),
  music: require('../assets/Images/music.png'),


  



  // gif
  mailGif: require('../assets/Images/mail.gif'),
};
