export default {
  getStarted: 'Get Started',
  onBoardingText1: 'Digital Banking Safety First',
  onBoardingText2: 'The easiest way to transaction and save your money',
  signIn: 'Sign In',
  loginTxt:
    'Get an account and control your finances better with full control of your budgets and savings.',
  email: 'Email',
  demoEmail: 'john@email.com',
  password: 'Password',
  remember: 'Remember',
  forgotPassword: 'Forgot Password',
  login: 'Log In',
  dontHaveAcc: 'Don’t have an account?',
  alreadyHaveAcc: 'Already have an Account ?',
  signUp: 'Sign Up',
  drivingVerification: ' Driving Verification Document',
  drivingLicense: 'Driving License',
  uploadMsg1: 'Upload your Front Driving Licence',
  uploadMsg2: 'File should be less than 5MB',
  uploadMsg3: 'Upload your Back Driving Licence',
  next: 'Next',
  buyNow: 'Buy Now',
  apply: 'Apply',
  payment: 'Payment',
  done: 'Done',
  welcomeBack: 'Welcome Back!',
  exp: 'Exp',
  future: 'Future',
  unlockYourSustainableCardAccount: 'Unlock your sustainable card account',
  saveTheClimateWithEachEuro: 'Save the climate with each Euro',
  saveMoneyInSubCard: 'Save money in sub-Card',
  payWithAbeautifulCard: 'Pay with a beautiful card',
  unlockDebitCard: 'Unlock Debit Card',
  changeCurrency: 'Change Currency',
  currentPackage: 'Current Package',
  changePassword: 'Change Password',
  payment: 'Payment',
  subscriptionPackages: 'Subscription Packages',
  manageCard: 'Manage Card',
  claim: 'Claim',
  payCycle: 'Pay Cycle',
  property: 'Property',
  transactions: 'Transactions',
  roundsUp: 'Rounds Up',
  termsAndConditions: 'Terms and Conditions',
  legaldocuments: 'Legal documents',
  helpSupport: 'Help & Support',
  referral: 'Referral',
  logout: 'Logout',
  acounts: 'Acounts',
  moreOptions: 'More Options',
  profile: 'Profile',
  save: 'Save',
  paymentMethod: 'Payment Method',
  Packages: 'Packages',
  expiresIn7Days: 'Expires in 7 Days',
  upgradePlan: 'Upgrade Plan',
  profile: 'Profile',
  save: 'Save',
  sendMoney: 'Send Money',
  receiveMoney: 'Receive Money',
  searchBeneficiary: 'Search Beneficiary',
  recent: 'Recent',
  yourContacts: 'Your Contacts',
  scanQrCode: 'Scan QR Code',
  scanQrMsg:
    'Please, place QR Code inside the frame to scan, also avoid shaking your Camera. This is to help you get results quickly.',
  enterYourAmount: 'Enter your amount',
  enterYourRequestAmount: 'Enter your Request Amount',
  selectYourCard: 'Select Your Card',
  cardStatus: 'Card Status',
  lockAndUnlockCard: 'Lock and Unlock card',
  controlYourCardUsageToKeepYourAccountSecure:
    'Control your card usage to keep your account secure',
  unlocked: 'Unlocked',
  whenYourCardisLockedYouWillNotBeAbleTo:
    'When your cardis locked you will not be able to:',
  viewReceipt: 'View Receipt',
  sendRequestSuccess: 'Send Request success',
  requestMoneyMsg: 'Request Money has been successfully done',
  reqAmtSend: 'Request Amount Send',
  rqMnyFrAny: 'Request Money from anyone',
  receiveMoneyMsg: 'You can request multiple payments from upto 20 people',
  searchPeople: 'Search People',
  qrCode: 'QR Code',
  requestAmount: 'Request Amount',
  myGoals: 'My Goals',
  continue: 'Continue',
  confirm: 'Confirm',
  amountGoals: 'Amount Goals',
  myProperty: 'My Property',
  monthlyPay: 'Monthly Pay',
  viewFullDetails: 'View Full Details',
  payAmount: 'Pay Amount',
  nextDue: 'Next Due',
  preview: 'Preview',
  monthlyRent: 'Monthly Rent',
  bedrooms: 'Bedrooms',
  bathrooms: 'Bathrooms',
  squareFeet: 'Square Feet',
  moveInSpecial: 'Move-in Special',
  pricingFloorPlans: 'Pricing & Floor Plans',
  tourThisFloorPlan: 'Tour This Floor Plan',
  buy: 'Buy',
  priceDetails: 'Price Details',
  freeSiteVisit: 'Free Site Visit',
  vehiclePrice: 'Vehicle Price',
  shippingfee: 'Shipping fee',
  TaxtitleRegistration: 'Tax, title, registration',
  totalPurchasePrice: 'Total Purchase Price',
  BuyNow: 'Buy Now',
  cashOut: 'Cash Out',
  addToMySpendings: 'Add to my spendings',
  AddToMyGoal: 'Add to my Goal',
  PrivacyPolicy: 'Privacy Policy',
  TermsCondition: 'Terms & Condition',
  iHaveAgreeWthThis: 'I have agree with this',
  decline: 'Decline',
  Documents: 'Documents',
  uploadIdPhoto: 'Upload ID Photo',
  positionTheFront: 'Position the front',
  frontOfDriversLicense: 'Front of Driver’s License',
  positionTheFrontOfYourLicenseInTheFrame:
    'Position the front of your license in the frame',
  backOfDriversLicense: 'Back of Driver’s License',
  positionTheBackOfYourLicenseInTheFrame:
    'Position the Back of your license in the frame',
  ContactsperActivation: '120 Contacts,$2 per activation',
  inviteFriend: 'Invite Friend',
  inviteAFriend: 'Invite a Friend',
  copyMyReferalLink: 'Copy my Referal Link',
  searchFinancialServicesSolutionOffice:
    'Search Financial Services Solution Office',
  FinancialServicesSolutionOffices: 'Financial Services Solution Offices',
  kycDocument: 'Kyc Document',
  LetUsknowYourPlaceOfResidenceAndMainOccupation:
    'Let us know your place of residence and main occupation',
  cancel: 'Cancel',
  monthlyPayment: 'Monthly Payment',
  currentMonth: 'Current Month',
  submit: 'Submit',
  letUsknowInWhichCountryAreYouSubjectToTax:
    'Let us know In which country are you subject to tax?',
  openYourAccount: 'Open your account',
  OpenOourMailApp: 'Open your mail app',
  verifyYourEmail: 'Verify your email',
  mobileNumber: 'Mobile Number',
  verifyIdentity: 'Verify Identity',
  timeToVerifyYourIdentityWithShortVideoCall:
    'Time to verify your identity with a short video call',
  AddNewCard: 'Add New Card',
  bankAccount: 'Bank Acount',
  data: 'Data',
  areYouSureYouWanttoClaimThisRequest: 'Are You Sure You Want to Claim This Request',
  yesDoIt: 'Yes Do It',
  fundDepositSuccessfully: 'Fund Deposit successfully',
  moneyhasbeenSuccessfullyDeposieYourFundPayment: 'Money has been successfully Deposie Your Fund Payment',
  electricityPay: 'Electricity Pay',
  change: 'Change',
  fillYourDetails: 'Fill Your Details',
  paySuccess: 'Pay Success',
  phoneRechage: 'Phone Recharge',
  selectRechargePlan: 'Select a Recharge Plan',
  rechargeSuccess: 'Recharge Success',
  billPay: 'Bill Pay',
  services: 'Services',
  insurance: 'Insurance',
  insuranceServices: 'Insurance Services',
  myPolicies: 'My Policies',
  active: 'Active',
  trackClaim: 'Track Claim',
  PolicyDocument: 'Policy Document',
  edit: 'Edit',
  overview: 'Overview',
  coverages: 'Coverages',
  carNumber: 'Car Number',
  vehicleInsurance: 'Vehicle Insurance',
  vehicleTaxt: 'Vehicle Taxt',
  typeOfInsurance: 'Type Of Insurance',
  time: 'Time',
  expireOfGuarantee: 'Expire of Guarantee',
  selectTheMembersYouWantToInsure: 'Select the members you want to insure',
  memberhavePreExistingEddress: 'Memberhave pre-existing address',
  selectPlan: 'Select Plan',
  investment: 'Investments',
  sharePrice: 'Share Price',
  amountRaised: 'Amount Raised',
  investNow: 'Invest  Now',
  accreitedInvestoresOnly: 'ACCREDITED INVESTORS ONLY',
  digitalRecipts: 'Digital Recipts',
  AllPaymentsRecipts: 'All Payments Recipts',
  paymentSuccess: 'Payment Success!',
  YourPaymentHasBeenSuccessfullydone: 'Your payment has been successfully done.',
  MarketPlace: 'MarketPlace',
  houseMarketplace: 'House Marketplace',
  autoMarketplace: 'Auto Marketplace',
  houses: 'Houses',
  townhomes: 'Townhomes',
  condos: 'Condos',
  apartment: 'Apartment',
  propertyType: 'Property Type',
  listOfPropertys : 'List of Propertys ',
  filter: 'Filter',
  clearAll: 'Clear All',
  price: 'Price',
  minRent: 'Min Rent',
  maxRent: 'Max Rent',
  beds: 'Beds',
  baths: 'Baths',
  Subscriptions: 'Subscriptions',
  autoPayment: 'Auto Payment',
  subscriptionPayments: 'Subscription Payments',
  payNow: 'Pay Now',
  selectFinancier: 'Select Financier',
};
